-- DATABASE: RecruiterDB
-- PLATFORM: MySQL 8+

-- 1. Create the base USERS table (Authentication and Core Identity)
CREATE TABLE users (
    id CHAR(36) PRIMARY KEY COMMENT 'UUID generated by application/auth system',
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('admin', 'applicant', 'recruiter') NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. PROFILES table (User-specific data and details)
CREATE TABLE profiles (
    id CHAR(36) PRIMARY KEY COMMENT 'Foreign Key to users.id',
    full_name VARCHAR(100) NOT NULL,
    user_type ENUM('applicant', 'recruiter') NOT NULL,
    domain VARCHAR(50), -- Applicant's preferred domain/specialization
    resume_path VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    
    FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE
);

-- 3. CLIENTS table (Hiring Companies/Agencies)
CREATE TABLE clients (
    id CHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    industry VARCHAR(50),
    website VARCHAR(255),
    company_size INT,
    account_manager_id CHAR(36),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,

    FOREIGN KEY (account_manager_id) REFERENCES users(id) ON DELETE SET NULL
);

-- 4. JOB_ADVERTS table (The open positions)
CREATE TABLE job_adverts (
    id CHAR(36) PRIMARY KEY,
    recruiter_id CHAR(36) NOT NULL,
    client_id CHAR(36) NOT NULL,
    title VARCHAR(255) NOT NULL,
    domain VARCHAR(50) NOT NULL,
    location VARCHAR(100) NOT NULL,
    job_type VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    requirements TEXT NOT NULL,
    salary_range VARCHAR(50),
    status ENUM('active', 'on_hold', 'filled') DEFAULT 'active' NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    
    FOREIGN KEY (recruiter_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);

-- 5. APPLICATIONS table (The central ATS link)
CREATE TABLE applications (
    id CHAR(36) PRIMARY KEY,
    job_id CHAR(36) NOT NULL,
    applicant_id CHAR(36) NOT NULL,
    resume_path VARCHAR(255) NOT NULL,
    ats_score INT DEFAULT 0,
    status ENUM('applied', 'screening', 'interview', 'offer', 'rejected', 'hired') DEFAULT 'applied' NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    
    UNIQUE KEY (job_id, applicant_id), -- Prevents duplicate applications
    
    FOREIGN KEY (job_id) REFERENCES job_adverts(id) ON DELETE CASCADE,
    FOREIGN KEY (applicant_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 6. CANDIDATE_INTERACTIONS table (Recruiter CRM/Audit Log)
CREATE TABLE candidate_interactions (
    id CHAR(36) PRIMARY KEY,
    candidate_id CHAR(36) NOT NULL, 
    recruiter_id CHAR(36) NOT NULL, 
    interaction_type ENUM('Call', 'Email', 'Note', 'Interview') NOT NULL,
    details TEXT NOT NULL,
    related_job_id CHAR(36),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,

    FOREIGN KEY (candidate_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (recruiter_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (related_job_id) REFERENCES job_adverts(id) ON DELETE SET NULL
);

-- 7. ATS_SCORE_HISTORY table (Tracking every score change for audit/analysis)
CREATE TABLE ats_score_history (
    id CHAR(36) PRIMARY KEY,
    application_id CHAR(36) NOT NULL,
    score_value INT NOT NULL,
    scorer_type VARCHAR(50) DEFAULT 'Mock API' NOT NULL, 
    scored_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,

    FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE
);

-- 8. EMAIL_LOG table (For Brevo/SMTP audit and queuing)
CREATE TABLE email_log (
    id CHAR(36) PRIMARY KEY,
    recipient_email VARCHAR(100) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    body_content TEXT NOT NULL,
    status ENUM('QUEUED', 'SENT', 'FAILED', 'DELIVERED') DEFAULT 'QUEUED' NOT NULL,
    related_application_id CHAR(36),
    sent_at DATETIME,
    error_details TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,

    FOREIGN KEY (related_application_id) REFERENCES applications(id) ON DELETE SET NULL
);
